import groovy.transform.Field

properties([disableConcurrentBuilds(abortPrevious: true)])
def DO_RUN=1
def TARGET="main"
def SCRIPT_LOCATION="contrib/intel/jenkins"
def RELEASE=0
@Field def BUILD_MODES=["reg", "dbg", "dl"]
@Field def MPI_TYPES=["impi", "mpich", "ompi"]
def PYTHON_VERSION="3.9"

def run_python(version, command, output=null) {
  if (output != null)
    sh "python$version $command >> $output"
  else
    sh "python$version $command"
}

def slurm_batch(partition, node_num, output, command) {
  try {
    sh """timeout 3600 sbatch --partition=${partition} -N ${node_num} \
          --wait -o ${output} --open-mode=append --wrap=\'env; ${command}\'
       """
  } catch (Exception e) {
    sh "scancel \$(cat ${output} | grep SLURM_JOBID | cut -d \"=\" -f 2)"
    sh "cat ${output}"
    error("Build failed ${e}")
  }
  sh "cat ${output}"
}

def run_fabtests(stage_name, partition, node_num, prov, util=null,
                 user_env=null) {
  def command = "python3.9 runtests.py"
  def opts = "--prov=${prov} --test=fabtests"
  if (util)
    opts = "${opts} --util=${util}"

  if (user_env)
    opts = "${opts} --user_env ${user_env}"

  for (mode in BUILD_MODES) {
    echo "Running $stage_name fabtests $mode"
    slurm_batch("${partition}", "${node_num}",
                "${env.LOG_DIR}/${stage_name}_fabtests_${mode}",
                "${command} ${opts} --ofi_build_mode=${mode}")
  }

  echo "${stage_name} completed."
}

def run_middleware(providers, stage_name, test, partition, node_num, mpi=null,
                   imb_grp=null) {
  def base_cmd = "python3.9 runtests.py --test=${test}"
  def opts = ""
  def prefix = "${env.LOG_DIR}/${stage_name}_"
  def suffix = "_${test}_reg"
  if (mpi) {
    base_cmd = "${base_cmd} --mpi=${mpi}"
    suffix = "_${mpi}${suffix}"
  }

  if (imb_grp)
    base_cmd = "${base_cmd} --imb_grp=${imb_grp}"

  for (prov in providers) {
    if (prov[1]) {
      echo "Running ${prov[0]}-${prov[1]} ${stage_name}"
      opts = "--prov=${prov[0]} --util=${prov[1]}"
      output = "${prefix}${prov[0]}-${prov[1]}${suffix}"
    } else {
      echo "Running ${prov[0]} ${stage_name}"
      opts = "--prov=${prov[0]}"
      output = "${prefix}${prov[0]}${suffix}"
    }

    slurm_batch("${partition}", "${node_num}", "${output}",
                "${base_cmd} ${opts}")
  }
}

def check_target() {
  echo "CHANGE_TARGET = ${env.CHANGE_TARGET}"
  if (changeRequest()) {
    TARGET = env.CHANGE_TARGET
  }

  if (TARGET) {
    return TARGET
  }

  return "main"
}

def release() {
  def file = "${env.WORKSPACE}/commit_id"
  if (!fileExists(file)) {
    echo "CI Run has not rebased with ofiwg/libfabric. Please Rebase."
    return 1
  }

  def changes = readFile file
  def changeStrings = new ArrayList<String>()

  for (line in changes.readLines()) {
    changeStrings.add(line)
  }

  if ((changeStrings.toArray().any { it =~ /(Makefile\.am)\b/ }) ||
      (changeStrings.toArray().any { it =~ /(configure\.ac)\b/ })) {
        echo "This is probably a release"
        return 1
  }

  return 0
}

def skip() {
  def file = "${env.WORKSPACE}/commit_id"
  if (!fileExists(file)) {
    echo "CI Run has not rebased with ofiwg/libfabric. Please Rebase."
    return 1
  }

  def changes = readFile file
  def changeStrings = new ArrayList<String>()

  for (line in changes.readLines()) {
    changeStrings.add(line)
  }

  echo "Changeset is: ${changeStrings.toArray()}"
  if (changeStrings.toArray().every { it =~ /(?:fabtests\/pytests|man|prov\/efa|prov\/opx).*$/ }) {
    echo "DONT RUN!"
    return 0
  }

  if (changeStrings.isEmpty()) {
    echo "DONT RUN!"
    return 0
  }

  return 1
}

pipeline {
  agent {
    node {
      label 'main'
      customWorkspace "workspace/${JOB_NAME}/${env.BUILD_NUMBER}"
    }
  }
  options {
      timestamps()
      timeout(activity: true, time: 1, unit: 'HOURS')
  }
  environment {
      JOB_CADENCE = 'PR'
      LOG_DIR = "${env.JOB_INSTALL_DIR}/${env.JOB_NAME}/${env.BUILD_NUMBER}/log_dir"
  }

  stages {
    stage ('parallel-builds') {
      when { equals expected: 1, actual: DO_RUN }
      parallel {
        stage ('build') {
          steps {
            script {
              echo "Copying build dirs."
              build_item="builddir"
              command="""${env.WORKSPACE}/${SCRIPT_LOCATION}/build.py \
                     --build_item="""
              run_python(PYTHON_VERSION, "${command}${build_item}")
              echo "Copying log dirs."
              build_item="logdir"
              if (RELEASE) {
                run_python(PYTHON_VERSION, "${command}${build_item} --release")
              } else {
                run_python(PYTHON_VERSION, "${command}${build_item}")
              }
              build_item="libfabric"
              for (mode in  BUILD_MODES) {
                echo "Building Libfabric $mode"
                build_item="libfabric"
                run_python(PYTHON_VERSION,
                           """${command}${build_item} \
                           --ofi_build_mode=$mode""")
                echo "Building Fabtests $mode"
                build_item="fabtests"
                run_python(PYTHON_VERSION,
                           """${command}${build_item} \
                           --ofi_build_mode=$mode""")
              }
            }
          }
        }
      }
    }
    stage('parallel-tests') {
      when { equals expected: 1, actual: DO_RUN }
      parallel {
        stage('ucx') {
          steps {
            script {
             command="""${env.WORKSPACE}/${SCRIPT_LOCATION}/build.py \
                      --ucx --build_item="""
              for (mode in  BUILD_MODES) {
                echo "Building Libfabric $mode"
                build_item="libfabric"
                run_python(PYTHON_VERSION,
                           """${command}${build_item} \
                           --ofi_build_mode=$mode""")
                echo "Building Fabtests $mode"
                build_item="fabtests"
                run_python(PYTHON_VERSION,
                           """${command}${build_item} \
                           --ofi_build_mode=$mode""")
              }
              dir ("${env.WORKSPACE}/${SCRIPT_LOCATION}/") {
                run_fabtests("ucx", "totodile", "2", "ucx")
              }
            }
          }
        }
      }
    }
    stage ('Summary') {
      when { equals expected: 1, actual: DO_RUN }
      steps {
        withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin/:$PYTHONPATH']) {
          sh """
            env
            (
              if [[ $RELEASE -eq 1 ]]; then
                python3.9 ${env.WORKSPACE}/${SCRIPT_LOCATION}/summary.py --summary_item=all --release
              else
                python3.9 ${env.WORKSPACE}/${SCRIPT_LOCATION}/summary.py --summary_item=all
              fi
              echo "------------"
              if [[ ${RELEASE} -eq 1 ]]; then
                mkdir -p ${env.WORKSPACE}/internal
                rm -rf ${env.WORKSPACE}/internal/*
                git clone https://${env.PAT}@github.com/${env.INTERNAL} ${env.WORKSPACE}/internal
                cd ${env.WORKSPACE}/internal
                mkdir -p ${env.WORKSPACE}/internal/summaries
                cp ${env.WORKSPACE}/summary_*.log ${env.WORKSPACE}/internal/summaries/
                git add ${env.WORKSPACE}/internal/summaries/
                git commit -am \"add ${env.JOB_NAME}'s summary\"
                git pull -r origin master
                git push origin master
              fi
            )
          """
        }
      }
    }
  }

  post {
    always {
      withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:$PYTHONPATH']) {
        sh "python3.9 ${env.WORKSPACE}/${SCRIPT_LOCATION}/summary.py --summary_item=all"
      }
    }
    success {
      withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:$PYTHONPATH']) {
        dir("${env.WORKSPACE}") {
          sh "python3.9 ${env.WORKSPACE}/${SCRIPT_LOCATION}/summary.py -v --summary_item=all"
        }
      }
    }
    aborted {
      node ('daos_head') {
        withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:$PYTHONPATH']) {
          dir ("${env.JOB_INSTALL_DIR}/${env.JOB_NAME}/${env.BUILD_NUMBER}/middlewares") {
            deleteDir()
          }
        }
      }
      node ('dsa') {
        withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:$PYTHONPATH']) {
          dir ("${env.JOB_INSTALL_DIR}/${env.JOB_NAME}/${env.BUILD_NUMBER}/middlewares") {
            deleteDir()
          }
        }
      }
      node ('ze') {
        withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:$PYTHONPATH']) {
          dir ("${env.JOB_INSTALL_DIR}/${env.JOB_NAME}/${env.BUILD_NUMBER}/middlewares") {
            deleteDir()
          }
        }
      }
      withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:$PYTHONPATH']) {
        dir ("${env.JOB_INSTALL_DIR}/${env.JOB_NAME}/${env.BUILD_NUMBER}/middlewares") {
          deleteDir()
        }
      }
    }
    cleanup {
      withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:$PYTHONPATH']) {
        dir ("${env.JOB_INSTALL_DIR}/${env.JOB_NAME}/${env.BUILD_NUMBER}") {
          deleteDir()
        }
        dir("${env.WORKSPACE}") {
          deleteDir()
        }
        dir("${env.WORKSPACE}@tmp") {
          deleteDir()
        }
      }
    }
  }
}
